/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Antenny.Client.OpenAPIDateConverter;

namespace Antenny.Model
{
    /// <summary>
    /// NewSubscription
    /// </summary>
    [DataContract(Name = "NewSubscription")]
    public partial class NewSubscription : IEquatable<NewSubscription>, IValidatableObject
    {
        /// <summary>
        /// Defines Region
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RegionEnum
        {
            /// <summary>
            /// Enum UsEast1 for value: us-east-1
            /// </summary>
            [EnumMember(Value = "us-east-1")]
            UsEast1 = 1,

            /// <summary>
            /// Enum UsEast2 for value: us-east-2
            /// </summary>
            [EnumMember(Value = "us-east-2")]
            UsEast2 = 2,

            /// <summary>
            /// Enum UsWest1 for value: us-west-1
            /// </summary>
            [EnumMember(Value = "us-west-1")]
            UsWest1 = 3,

            /// <summary>
            /// Enum UsWest2 for value: us-west-2
            /// </summary>
            [EnumMember(Value = "us-west-2")]
            UsWest2 = 4,

            /// <summary>
            /// Enum ApNortheast1 for value: ap-northeast-1
            /// </summary>
            [EnumMember(Value = "ap-northeast-1")]
            ApNortheast1 = 5,

            /// <summary>
            /// Enum ApNortheast2 for value: ap-northeast-2
            /// </summary>
            [EnumMember(Value = "ap-northeast-2")]
            ApNortheast2 = 6,

            /// <summary>
            /// Enum ApSoutheast1 for value: ap-southeast-1
            /// </summary>
            [EnumMember(Value = "ap-southeast-1")]
            ApSoutheast1 = 7,

            /// <summary>
            /// Enum ApSoutheast2 for value: ap-southeast-2
            /// </summary>
            [EnumMember(Value = "ap-southeast-2")]
            ApSoutheast2 = 8,

            /// <summary>
            /// Enum EuCentral1 for value: eu-central-1
            /// </summary>
            [EnumMember(Value = "eu-central-1")]
            EuCentral1 = 9,

            /// <summary>
            /// Enum EuWest1 for value: eu-west-1
            /// </summary>
            [EnumMember(Value = "eu-west-1")]
            EuWest1 = 10,

            /// <summary>
            /// Enum EuWest2 for value: eu-west-2
            /// </summary>
            [EnumMember(Value = "eu-west-2")]
            EuWest2 = 11

        }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [DataMember(Name = "region", EmitDefaultValue = false)]
        public RegionEnum Region { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NewSubscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NewSubscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NewSubscription" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="customerId">customerId (required).</param>
        /// <param name="region">region (required).</param>
        /// <param name="resource">resource (required).</param>
        /// <param name="endpoint">endpoint (required).</param>
        public NewSubscription(string name = default(string), Guid customerId = default(Guid), RegionEnum region = default(RegionEnum), Resource resource = default(Resource), Endpoint endpoint = default(Endpoint))
        {
            this.CustomerId = customerId;
            this.Region = region;
            // to ensure "resource" is required (not null)
            this.Resource = resource ?? throw new ArgumentNullException("resource is a required property for NewSubscription and cannot be null");
            // to ensure "endpoint" is required (not null)
            this.Endpoint = endpoint ?? throw new ArgumentNullException("endpoint is a required property for NewSubscription and cannot be null");
            this.Name = name;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        [DataMember(Name = "resource", EmitDefaultValue = false)]
        public Resource Resource { get; set; }

        /// <summary>
        /// Gets or Sets Endpoint
        /// </summary>
        [DataMember(Name = "endpoint", EmitDefaultValue = false)]
        public Endpoint Endpoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NewSubscription {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  Resource: ").Append(Resource).Append("\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NewSubscription);
        }

        /// <summary>
        /// Returns true if NewSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of NewSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NewSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CustomerId == input.CustomerId ||
                    (this.CustomerId != null &&
                    this.CustomerId.Equals(input.CustomerId))
                ) && 
                (
                    this.Region == input.Region ||
                    this.Region.Equals(input.Region)
                ) && 
                (
                    this.Resource == input.Resource ||
                    (this.Resource != null &&
                    this.Resource.Equals(input.Resource))
                ) && 
                (
                    this.Endpoint == input.Endpoint ||
                    (this.Endpoint != null &&
                    this.Endpoint.Equals(input.Endpoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.CustomerId != null)
                    hashCode = hashCode * 59 + this.CustomerId.GetHashCode();
                hashCode = hashCode * 59 + this.Region.GetHashCode();
                if (this.Resource != null)
                    hashCode = hashCode * 59 + this.Resource.GetHashCode();
                if (this.Endpoint != null)
                    hashCode = hashCode * 59 + this.Endpoint.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if(this.Name != null && this.Name.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 32.", new [] { "Name" });
            }

            // Name (string) minLength
            if(this.Name != null && this.Name.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 3.", new [] { "Name" });
            }

            yield break;
        }
    }

}
