/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Antenny.Client;
using Antenny.Model;

namespace Antenny.API
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a list of events for a subscription
        /// </summary>
        /// <remarks>
        /// Lists events for a subscription
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <returns>EventList</returns>
        EventList ListEvents(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string));

        /// <summary>
        /// Gets a list of events for a subscription
        /// </summary>
        /// <remarks>
        /// Lists events for a subscription
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <returns>ApiResponse of EventList</returns>
        ApiResponse<EventList> ListEventsWithHttpInfo(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets a list of events for a subscription
        /// </summary>
        /// <remarks>
        /// Lists events for a subscription
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventList</returns>
        System.Threading.Tasks.Task<EventList> ListEventsAsync(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a list of events for a subscription
        /// </summary>
        /// <remarks>
        /// Lists events for a subscription
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventList)</returns>
        System.Threading.Tasks.Task<ApiResponse<EventList>> ListEventsWithHttpInfoAsync(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApi : IEventsApiSync, IEventsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EventsApi : IEventsApi
    {
        private Antenny.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi(String basePath)
        {
            this.Configuration = Antenny.Client.Configuration.MergeConfigurations(
                Antenny.Client.GlobalConfiguration.Instance,
                new Antenny.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EventsApi(Antenny.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Antenny.Client.Configuration.MergeConfigurations(
                Antenny.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EventsApi(Antenny.Client.ISynchronousClient client, Antenny.Client.IAsynchronousClient asyncClient, Antenny.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Antenny.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Antenny.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Antenny.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Antenny.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets a list of events for a subscription Lists events for a subscription
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <returns>EventList</returns>
        public EventList ListEvents(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string))
        {
            Antenny.Client.ApiResponse<EventList> localVarResponse = ListEventsWithHttpInfo(subId, sort, level, limit, startKey);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of events for a subscription Lists events for a subscription
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <returns>ApiResponse of EventList</returns>
        public Antenny.Client.ApiResponse<EventList> ListEventsWithHttpInfo(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string))
        {
            Antenny.Client.RequestOptions localVarRequestOptions = new Antenny.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Antenny.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Antenny.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("subId", Antenny.Client.ClientUtils.ParameterToString(subId)); // path parameter
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (level != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "level", level));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (startKey != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "startKey", startKey));
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<EventList>("/subscriptions/{subId}/events", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a list of events for a subscription Lists events for a subscription
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventList</returns>
        public async System.Threading.Tasks.Task<EventList> ListEventsAsync(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Antenny.Client.ApiResponse<EventList> localVarResponse = await ListEventsWithHttpInfoAsync(subId, sort, level, limit, startKey, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of events for a subscription Lists events for a subscription
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subId">Subscription id</param>
        /// <param name="sort">Defines sort direction (optional)</param>
        /// <param name="level">Filters events by level (optional)</param>
        /// <param name="limit">Limits the number of returned items (optional)</param>
        /// <param name="startKey">Defines start of page of results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventList)</returns>
        public async System.Threading.Tasks.Task<Antenny.Client.ApiResponse<EventList>> ListEventsWithHttpInfoAsync(Guid subId, string sort = default(string), string level = default(string), int? limit = default(int?), string startKey = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Antenny.Client.RequestOptions localVarRequestOptions = new Antenny.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Antenny.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Antenny.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("subId", Antenny.Client.ClientUtils.ParameterToString(subId)); // path parameter
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (level != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "level", level));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (startKey != null)
            {
                localVarRequestOptions.QueryParameters.Add(Antenny.Client.ClientUtils.ParameterToMultiMap("", "startKey", startKey));
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<EventList>("/subscriptions/{subId}/events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
