/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Antenny.Client;
using Antenny.Model;

namespace Antenny.API
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegistrationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a customers registration
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <returns>Registration</returns>
        Registration GetRegistration(Guid custId);

        /// <summary>
        /// Gets a customers registration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <returns>ApiResponse of Registration</returns>
        ApiResponse<Registration> GetRegistrationWithHttpInfo(Guid custId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegistrationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets a customers registration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Registration</returns>
        System.Threading.Tasks.Task<Registration> GetRegistrationAsync(Guid custId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a customers registration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Registration)</returns>
        System.Threading.Tasks.Task<ApiResponse<Registration>> GetRegistrationWithHttpInfoAsync(Guid custId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegistrationApi : IRegistrationApiSync, IRegistrationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RegistrationApi : IRegistrationApi
    {
        private Antenny.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RegistrationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RegistrationApi(String basePath)
        {
            this.Configuration = Antenny.Client.Configuration.MergeConfigurations(
                Antenny.Client.GlobalConfiguration.Instance,
                new Antenny.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RegistrationApi(Antenny.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Antenny.Client.Configuration.MergeConfigurations(
                Antenny.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Antenny.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RegistrationApi(Antenny.Client.ISynchronousClient client, Antenny.Client.IAsynchronousClient asyncClient, Antenny.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Antenny.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Antenny.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Antenny.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Antenny.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Antenny.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets a customers registration 
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <returns>Registration</returns>
        public Registration GetRegistration(Guid custId)
        {
            Antenny.Client.ApiResponse<Registration> localVarResponse = GetRegistrationWithHttpInfo(custId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a customers registration 
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <returns>ApiResponse of Registration</returns>
        public Antenny.Client.ApiResponse<Registration> GetRegistrationWithHttpInfo(Guid custId)
        {
            Antenny.Client.RequestOptions localVarRequestOptions = new Antenny.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Antenny.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Antenny.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custId", Antenny.Client.ClientUtils.ParameterToString(custId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Registration>("/customers/{custId}/registration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRegistration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a customers registration 
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Registration</returns>
        public async System.Threading.Tasks.Task<Registration> GetRegistrationAsync(Guid custId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Antenny.Client.ApiResponse<Registration> localVarResponse = await GetRegistrationWithHttpInfoAsync(custId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a customers registration 
        /// </summary>
        /// <exception cref="Antenny.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="custId">Customer Id for registration</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Registration)</returns>
        public async System.Threading.Tasks.Task<Antenny.Client.ApiResponse<Registration>> GetRegistrationWithHttpInfoAsync(Guid custId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Antenny.Client.RequestOptions localVarRequestOptions = new Antenny.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Antenny.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Antenny.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custId", Antenny.Client.ClientUtils.ParameterToString(custId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Registration>("/customers/{custId}/registration", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRegistration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
