/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Antenny.API;
using Antenny.Model;
using Antenny.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing EventList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventList
        //private EventList instance;

        public EventListTests()
        {
            // TODO uncomment below to create an instance of EventList
            //instance = new EventList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventList
        /// </summary>
        [Fact]
        public void EventListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventList
            //Assert.IsInstanceOfType<EventList> (instance, "variable 'instance' is a EventList");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'LastKey'
        /// </summary>
        [Fact]
        public void LastKeyTest()
        {
            // TODO unit test for the property 'LastKey'
        }

    }

}
