/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Antenny.API;
using Antenny.Model;
using Antenny.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing Message
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Message
        //private Message instance;

        public MessageTests()
        {
            // TODO uncomment below to create an instance of Message
            //instance = new Message();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Message
        /// </summary>
        [Fact]
        public void MessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Message
            //Assert.IsInstanceOfType<Message> (instance, "variable 'instance' is a Message");
        }


        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
