/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Antenny.API;
using Antenny.Model;
using Antenny.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing NewClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewClientTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewClient
        //private NewClient instance;

        public NewClientTests()
        {
            // TODO uncomment below to create an instance of NewClient
            //instance = new NewClient();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewClient
        /// </summary>
        [Fact]
        public void NewClientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewClient
            //Assert.IsInstanceOfType<NewClient> (instance, "variable 'instance' is a NewClient");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
