/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Antenny.API;
using Antenny.Model;
using Antenny.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing NewSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewSubscription
        //private NewSubscription instance;

        public NewSubscriptionTests()
        {
            // TODO uncomment below to create an instance of NewSubscription
            //instance = new NewSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewSubscription
        /// </summary>
        [Fact]
        public void NewSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewSubscription
            //Assert.IsInstanceOfType<NewSubscription> (instance, "variable 'instance' is a NewSubscription");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Fact]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }

    }

}
