/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Antenny.API;
using Antenny.Model;
using Antenny.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing Registration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Registration
        //private Registration instance;

        public RegistrationTests()
        {
            // TODO uncomment below to create an instance of Registration
            //instance = new Registration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Registration
        /// </summary>
        [Fact]
        public void RegistrationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Registration
            //Assert.IsInstanceOfType<Registration> (instance, "variable 'instance' is a Registration");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Clients'
        /// </summary>
        [Fact]
        public void ClientsTest()
        {
            // TODO unit test for the property 'Clients'
        }
        /// <summary>
        /// Test the property 'Subscriptions'
        /// </summary>
        [Fact]
        public void SubscriptionsTest()
        {
            // TODO unit test for the property 'Subscriptions'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

    }

}
