/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Antenny.Client;
using Antenny.API;
using Antenny.Model;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing ClientApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ClientApiTests : IDisposable
    {
        private ClientApi instance;

        public ClientApiTests()
        {
            instance = new ClientApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ClientApi
            //Assert.IsType(typeof(ClientApi), instance, "instance is a ClientApi");
        }

        
        /// <summary>
        /// Test CreateClient
        /// </summary>
        [Fact]
        public void CreateClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewClient newClient = null;
            //var response = instance.CreateClient(newClient);
            //Assert.IsType<ModelClient> (response, "response is ModelClient");
        }
        
        /// <summary>
        /// Test DeleteClient
        /// </summary>
        [Fact]
        public void DeleteClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid clientId = null;
            //instance.DeleteClient(clientId);
            
        }
        
        /// <summary>
        /// Test GetClient
        /// </summary>
        [Fact]
        public void GetClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid clientId = null;
            //var response = instance.GetClient(clientId);
            //Assert.IsType<ModelClient> (response, "response is ModelClient");
        }
        
        /// <summary>
        /// Test ListClients
        /// </summary>
        [Fact]
        public void ListClientsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid custId = null;
            //string sort = null;
            //int? limit = null;
            //string startKey = null;
            //var response = instance.ListClients(custId, sort, limit, startKey);
            //Assert.IsType<ClientList> (response, "response is ClientList");
        }
        
    }

}
