/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Antenny.Client;
using Antenny.API;
using Antenny.Model;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing RegistrationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RegistrationApiTests : IDisposable
    {
        private RegistrationApi instance;

        public RegistrationApiTests()
        {
            instance = new RegistrationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegistrationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RegistrationApi
            //Assert.IsType(typeof(RegistrationApi), instance, "instance is a RegistrationApi");
        }

        
        /// <summary>
        /// Test GetRegistration
        /// </summary>
        [Fact]
        public void GetRegistrationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid custId = null;
            //var response = instance.GetRegistration(custId);
            //Assert.IsType<Registration> (response, "response is Registration");
        }
        
    }

}
