/*
 * Antenny API
 *
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Antenny.Client;
using Antenny.API;
using Antenny.Model;

namespace Antenny.Test
{
    /// <summary>
    ///  Class for testing SubscriptionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SubscriptionApiTests : IDisposable
    {
        private SubscriptionApi instance;

        public SubscriptionApiTests()
        {
            instance = new SubscriptionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SubscriptionApi
            //Assert.IsType(typeof(SubscriptionApi), instance, "instance is a SubscriptionApi");
        }

        
        /// <summary>
        /// Test CancelSubscription
        /// </summary>
        [Fact]
        public void CancelSubscriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid subId = null;
            //InlineObject inlineObject = null;
            //instance.CancelSubscription(subId, inlineObject);
            
        }
        
        /// <summary>
        /// Test CreateSubscription
        /// </summary>
        [Fact]
        public void CreateSubscriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewSubscription newSubscription = null;
            //var response = instance.CreateSubscription(newSubscription);
            //Assert.IsType<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test GetSubscription
        /// </summary>
        [Fact]
        public void GetSubscriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid subId = null;
            //var response = instance.GetSubscription(subId);
            //Assert.IsType<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test ListSubscriptions
        /// </summary>
        [Fact]
        public void ListSubscriptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid custId = null;
            //string sort = null;
            //int? limit = null;
            //string startKey = null;
            //var response = instance.ListSubscriptions(custId, sort, limit, startKey);
            //Assert.IsType<SubscriptionList> (response, "response is SubscriptionList");
        }
        
    }

}
